title: Intro to  Engineering Values
description: >-
  There are millions of projects at [Customer], all competing for attention from the
  millions of [Customer] Developers to help. Learn how to help your project stand out
  and build up the [Customer] Engineering Values.
template:
  repo: intro-to-[Customer]-engineering-values-template
  name: intro-to-[Customer]-engineering-values
  description: 'Testing Course Creation '
before:
  - type: createIssue
    title: Welcome to the Engineering Value course.
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
